@baseUrl = http://127.0.0.1:3000/api

### hello-world

GET {{baseUrl}}/hello-world

### test

POST {{baseUrl}}/test
Content-Type: application/json

{
    "name": "John Doe"
}

### generate-image

POST {{baseUrl}}/generate-image
Content-Type: application/json

{
    "prompt": "",
    "userId": "123"
}

### get-wallpapera

GET {{baseUrl}}/get-wallpapers
