export default function Hero() {
  return (
    <div className="bg-white">
      <div className="mx-auto px-6 mt-8 md:pt-16 md:pb-8 lg:px-8">
        <h1 className="text-primary text-3xl font-bold tracking-tight text-gray-900 md:text-6xl lg:text-8xl">
          AI powered wallpaper generator
        </h1>
        <div className="text-gray-400 mt-10 flex items-center text-lg md:text-2xl">
          Input a simple prompt to get a facinating wallpaper generated by AI.Like "A real asian beauty" or "A beautiful sunset" .
        </div>
      </div>
    </div>
  );
}
